# pyproject.toml
[tool.ruff]
format = "grouped"
line-length = 120
show-source = true
target-version = "py311"

select = ["ALL"]
ignore = [
  "D100",
  "D103",
  "D102",
  "D101",
  "D107",
  "D203",
  "D213",
  "D419",
  "ERA001",
  "A001",
  "N802",
  "N803",
  "N806",
  "F841",
  "A001",
  "ANN001",
  "ANN201",
  "ANN202",
  "ANN204",
  "ARG001",
  "ANN002",
  "E501",
  "E701",
  "E702",
  "E101",
  "ANN101",
  "Q000",
  "Q001",
  "F405",
  "F403",
  "BLE001",
  "FBT003",
  "S311",
  "PLR5501",
  "PLR2004",
  "B007",
  "C901",
  "PLR0915",
  "PLR0912",
  "PLC1901",
  "E712",
  "E711",
  "RET506",
  "RET505",
  "RET503",
  "TRY301",
  "PLW0120",
  "SIM116",
  "UP008",
  "SIM300",
  "SIM114",
  "ARG002",
  "SIM401",
  "UP015",
  "F811",
  "PLW2901",
  "TD002",
  "TD003",
  "TD004",
  "TD005",
  "COM819",
  "PLR0913",
  "C416",
  "ISC003",
  "SIM102",
  "E402",
  "F811",
  "E401",
  "TRY300",
  "PTH100",
  "F821",
  "T201",
  "ARG005",
  "E722",
  "W191",
  "RET504",
  "FIX002",
  "D105",
  "I001",
  "PLR0911",
  "INP001",
  "E721",
]